### ISSUE TITLE
Question: Typescript Support

### ISSUE THREAD

**Issue by tzarger** [nearform/fastify-ravendb#16]
Hello, not an issue, just a question.

This looks great. When looking the example `multiple-dbs-with-session` Typescript came to mind. Are there plans for Typescript support?

**Comment by simoneb** [comment]
Although the codebase is JS, TS is supported thanks to the type definitions in https://github.com/nearform/fastify-ravendb/blob/master/index.d.ts

**Comment by tzarger** [comment]
@simoneb So sorry I did not see that. Thanks for the awesome project.
