### ISSUE TITLE
Request: Add RavenDB Conventions

### ISSUE THREAD

**Issue by tzarger** [nearform/fastify-ravendb#17]
Hello, this looks great as mentioned in my last question. Based on the Typescript d.ts you sent in my last question, do you think you could also add support for conventions:

```
store.conventions.storeDatesInUtc = true;
store.conventions.registerEntityType(model)
```
I use several of the `conventions` properties in my code.

I really think that might be an addition that others might use as well. Looking forward to possibly using this project. Thanks again.

**Comment by simoneb** [comment]
The document store is exposed via the server.rvn decorator as described in the docs, I guess that should do, right?

**Comment by tzarger** [comment]
Hello, I know the store is exposed, but wouldn't that mean you have to do on a request by request and the conventions are set one time with store creation, which I would think you would set this when `registering the plugin`. This is similar to the option `findCollectionNameForObjectLiteral` you have in the d.ts ... You set it and forget it and for Typescript you really need to have the option `store.conventions.registerEntityType(model)`

Does that make sense, or am I looking at this wrong?

**Comment by simoneb** [comment]
We can't expose via the registration options all the possible operations that you can do with the store. The store is a server global, so you can simply do:

```js
await fastify.register(fastifyRavenDB, { ... })

// here you have access to fastify.rvn, which is the store
fastify.rvn.conventions.whatever
```
