### ISSUE TITLE
Publicize plugin on fastify and ravendb communities

### ISSUE THREAD

**Issue by simoneb** [nearform/fastify-ravendb#4]
https://www.fastify.io/docs/latest/Guides/Ecosystem/
https://github.com/ravendb/ravendb/discussions

**Comment by drakhart** [comment]
Fastify ecosystem: https://github.com/fastify/fastify/pull/4277

**Comment by drakhart** [comment]
RavenDB community (proposal): https://docs.google.com/document/d/1D87UE4fzjkPznrussUTc6XTTNT-GvId-SyLTja8s5Hw

**Comment by drakhart** [comment]
RavenDB community: https://github.com/ravendb/ravendb/discussions/15011
